version: "3"
services:
  # Database layer >> MySql db
  mysql_database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp_db
      MYSQL_USER: asmaa
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql   
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_database
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp_db
    volumes: ['./:/var/www/html']
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  mysql: {}